### ISSUE TITLE
In case 3D printer is paused you should get the notification about it

### ISSUE THREAD

**Issue by Actpohomoc** [bruhautomation/BRUH3-Home-Assistant-Configuration#3]
My proposition to you is to use filament out sensor for your 3D printer.
And in case of this situation 3D printer will change the state to "Paused".
You should have the notification about it.
Something like 
```
- id: 3d_printer_paused_notify
  alias: 3D printer paused notify
  trigger:
  - entity_id: sensor.octoprint_current_state
    platform: state
    to: 'Paused'
  action:
    service: notify.notify
    data_template:
      message: '!!! 3D printer PAUSED now !!! In case of ends of filament need to turn off the temperature!'

```

https://www.thingiverse.com/search/page:1?q=filament+sensor&sa=&dwh=755922bd0c86fee
